pipeline {
    agent any

    parameters {
        choice(choices: ["TEST", "DEV", "PRE-PRD","PRD"], description: "Which environment to deploy in ?", name: "deployEnv")
    }

    stages {
        stage("Demo") {
            steps{
                echo "choice is set to: ${params.deployEnv}"
            }
        }
    }
}